spring:
  application:
    name: hello-spring-cloud-web-admin-feign
    thymeleaf:
      cache: false
      mode: LEGACYHTML5
      encoding: UTF-8
      servlet:
        content-type: text/html
        
        
server:
  port: 8765

feign:
  hystrix:
    enabled: true

eureka:
  client:
    eureka-server-u-r-l-context: http://localhost:8761/eureka
